Index subgraphs from the genesis block rather than block 1
graphprotocol/graph-node pull request #1297
Opened 2019-10-20 00:22 UTC by Jannis

This makes the latest Ethereum block pointer of subgraph deployments optional. New deployments are then initialized with the block pointer set to `None`. This instructs the block stream to start with block number 0 (genesis) instead of the next block after the current block pointer.

@leoyvens Any ideas for a good test for this?

2019-10-20 16:08 UTC, leoyvens commented
On testing, since the block stream is high up in the stack, imo it makes more sense to use black box testing for it. It would be a test that runs a graph-node, deploys a subgraph, subscribes to the indexing progress and asserts the result of a query. Doesn't seem too difficult and it's about time we start writing tests like that, but maybe we want to do it separately from this PR.

2019-10-21 17:23 UTC, Jannis commented
@leoyvens I agree, this would best be tested using integration tests.

For now, I've updated all tests that were affected by this change.

2019-10-22 18:08 UTC, leoyvens requested changes
If syncing doesn't start well it can't end well 😛 

Just one significant comment.

2019-10-22 18:42 UTC, Jannis commented on core/src/subgraph/registrar.rs
> +            .expect("cannot identify minimum start block because there are no data sources")
I'll double-check. Having at least one data source is a check we should apply before accepting a new subgraph deployment. I'll add that if we don't do it already.

2019-10-29 20:00 UTC, leoyvens commented
#1318 conflicted this a bit more, sorry.

2019-10-30 22:06 UTC, leoyvens commented on core/src/subgraph/registrar.rs
> +                    .map(move |block_ptr| Some(block_ptr))
You can write this as just `.map(Some)`.

2019-10-30 23:22 UTC, Jannis commented on core/src/subgraph/registrar.rs
> +            .expect("cannot identify minimum start block because there are no data sources")
I've added a validation rule here:
https://github.com/graphprotocol/graph-node/blob/e1622e1d3f114f7aa117aa1e1844ba8bad33455d/core/src/subgraph/validation.rs#L8-L11

2019-10-30 23:24 UTC, Jannis commented
@leoyvens I've added validation for there being at least one data source, and also addressed the latest review comments.

2019-10-31 00:05 UTC, Jannis commented
I'm not sure yet why this is but it's logging a lot of `Requesting 1 block(s)` messages now. I don't think those were there before:
```
Oct 31 00:03:56.921 INFO Scanning blocks [4120000, 4129999], subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager > BlockStream
Oct 31 00:03:56.921 DEBG Requesting logs for blocks [4120000, 4129999], contract 0xc611c82150b56e6e4ec5973acaba8835dd0d75a2, 3 events, subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager > BlockStream
Oct 31 00:03:57.084 DEBG Found 0 relevant block(s), subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager > BlockStream
Oct 31 00:03:57.085 DEBG Requesting 1 block(s), subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager > BlockStream
Oct 31 00:03:57.428 INFO Scanning blocks [4130000, 4139999], subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager > BlockStream
Oct 31 00:03:57.429 DEBG Requesting logs for blocks [4130000, 4139999], contract 0xc611c82150b56e6e4ec5973acaba8835dd0d75a2, 3 events, subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager > BlockStream
Oct 31 00:03:57.599 DEBG Found 0 relevant block(s), subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager > BlockStream
Oct 31 00:03:57.601 DEBG Requesting 1 block(s), subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager > BlockStream
Oct 31 00:03:57.945 INFO Scanning blocks [4140000, 4149999], subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager > BlockStream
Oct 31 00:03:57.946 DEBG Requesting logs for blocks [4140000, 4149999], contract 0xc611c82150b56e6e4ec5973acaba8835dd0d75a2, 3 events, subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager > BlockStream
Oct 31 00:03:58.109 DEBG Found 0 relevant block(s), subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager > BlockStream
Oct 31 00:03:58.110 DEBG Requesting 1 block(s), subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager > BlockStream
```

2019-10-31 00:08 UTC, leoyvens commented
@Jannis that was introduced in #1308, we now always grab the last block in the range so we can process it, even when it has no triggers.

2019-10-31 00:13 UTC, Jannis commented
@leoyvens Ah, great. Yes, I just verified it also happens on master, so it's independent.

I can confirm that on `master`, block `0` is skipped:
```
Oct 31 00:10:31.239 DEBG Starting block stream, subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager
Oct 31 00:10:31.865 INFO Scanning blocks [1, 100000], subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager > BlockStream
Oct 31 00:10:31.865 DEBG Requesting logs for blocks [1, 100000], contract 0xc611c82150b56e6e4ec5973acaba8835dd0d75a2, 3 events, subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager > BlockStream
Oct 31 00:10:32.493 DEBG Found 0 relevant block(s), subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager > BlockStream
Oct 31 00:10:32.495 DEBG Requesting 1 block(s), subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager > BlockStream
Oct 31 00:10:33.750 INFO Scanning blocks [100001, 200000], subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager > BlockStream
Oct 31 00:10:33.750 DEBG Requesting logs for blocks [100001, 200000], contract 0xc611c82150b56e6e4ec5973acaba8835dd0d75a2, 3 events, subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager > BlockStream
```

But with this PR, it's included:
```
Oct 31 00:13:33.874 DEBG Starting block stream, subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager
Oct 31 00:13:33.881 DEBG Received chain head update, head_block_number: 11753655, head_block_hash: 0x6dec…086a, network: poa-core, component: Store > ChainHeadUpdateListener
Oct 31 00:13:33.882 INFO Scanning blocks [0, 99999], subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager > BlockStream
Oct 31 00:13:33.882 DEBG Requesting logs for blocks [0, 99999], contract 0xc611c82150b56e6e4ec5973acaba8835dd0d75a2, 3 events, subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager > BlockStream
Oct 31 00:13:34.551 DEBG Found 0 relevant block(s), subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager > BlockStream
Oct 31 00:13:34.552 DEBG Requesting 1 block(s), subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager > BlockStream
Oct 31 00:13:35.687 INFO Syncing 1 blocks from Ethereum., code: BlockIngestionStatus, network_name: poa-core, blocks_needed: 1, blocks_behind: 1, latest_block_head: 11753656, current_block_head: 11753655, component: BlockIngestor
Oct 31 00:13:35.687 INFO Block 0x4b60…5733 contains no transactions, component: BlockIngestor
Oct 31 00:13:35.695 DEBG Received chain head update, head_block_number: 11753656, head_block_hash: 0x4b60…5733, network: poa-core, component: Store > ChainHeadUpdateListener
Oct 31 00:13:35.820 INFO Scanning blocks [100000, 199999], subgraph_id: QmW6P2YHdBqf6eGEmoK9suEs4yesiG1Z3K8UbrbME21qQS, component: SubgraphInstanceManager > BlockStream
```

2019-10-31 14:32 UTC, leoyvens approved these changes

2019-11-01 08:11 UTC, merged