Limit JSON-RPC retries
graphprotocol/graph-node pull request #1396
Opened 2019-12-06 15:01 UTC by leoyvens

So that we don't get stuck, for example requesting a block hash that got reorged. The block stream already resets on error so this will not fail the subgraph.

2019-12-06 17:22 UTC, lutter requested changes
Could you also document this environment variable in `docs/environment-variables.md`? Other than that, looks good to me.

2019-12-06 21:17 UTC, Jannis commented
@leoyvens The changes look good. Could you briefly explain how this is not failing the subgraph but resets the block stream and tries again _outside_ the adapter. I forgot how that worked.

2019-12-07 13:54 UTC, Jannis commented
Heh, wait. Isn't this more or less the same as https://github.com/graphprotocol/graph-node/pull/1277/files?

2019-12-09 15:35 UTC, leoyvens commented
@Jannis it is 🤦‍♂. The difference is that this only limits retries for calls used in the block stream. For example I'm not sure if limiting retries in the block ingestor would be prudent.

I like the env var name in that PR better so I renamed it in this PR, and documented it.

2019-12-09 18:13 UTC, Jannis commented
@leoyvens I think my PR caused more drastic failures in situations where they weren't desirable. So let's go with yours.

2019-12-09 18:13 UTC, Jannis approved these changes

2019-12-09 18:24 UTC, lutter approved these changes

2019-12-09 18:25 UTC, merged