Partial multi blockchain refactor
graphprotocol/graph-node pull request #1614
Opened 2020-04-21 11:42 UTC by Jannis

NOTE: I'm still cleaning this up.

2020-04-21 17:52 UTC, leoyvens commented
> We can bring it back but I felt like this was a good time to kill it.

When we tried just adding a deprecation warning for it, people protested. If we want to try this again, it would be more gentle to start with a deprecation warning.

2020-04-21 18:07 UTC, Jannis commented
@leoyvens I'll bring it back, should be easy enough.

2020-04-22 22:27 UTC, lutter commented on graph/src/components/networks/mod.rs
> +pub struct NetworkInstanceId {
Could you add a comment explaining what such an id signifies? Is this something like `ethereum/mainnet` where `ethereum` is the `network` and `name` is the specific instance?

2020-04-23 00:43 UTC, lutter requested changes
This PR is massive, and I can't say I've followed all that much of what it is doing. The PR puts a number of abstractions in place that will only have one implementer for the foreseeable future; how sure are we that all these abstractions will be what we need when we work on multi-blockchain? Are there changes that could be cut? I do like though how some of them componentize Ethereum-specific concepts.

2020-04-23 00:43 UTC, lutter commented on chain/ethereum/src/chain/mod.rs
> +    std::mem::forget(transport_event_loop);
Would it be better to store it in the `Connection` so it gets dropped when the connection gets dropped? That way, there's no leak.

2021-04-02 14:29 UTC, leoyvens commented
This is hopelessly conflicted and have a modified plan for multi-blockchain, so closing this PR.

2021-04-02 14:29 UTC, closed without merging