Don't crash node and show better error on invalid subgraph transitions
graphprotocol/graph-node pull request #1903
Opened 2020-09-14 13:02 UTC by Jannis

When a subgraph is indexed by two or more graph nodes that share a database, we're currently crashing nodes when they run into from/to block conflicts. What we should do (and what this PR does) is only make the subgraph fail and also print a message that points out the likely cause of the issue: that multiple nodes are indexing the same subgraph.

2020-09-15 16:04 UTC, lutter requested changes
This all looks great. My only issue is calling this a 'subgraph transition' which makes me think subgraphs move through various states. What we are really complaining about is that we are trying to process blocks again (or, more precisely, write the result of processing blocks) that we were already done with.

Can we call this something like `DuplicateBlockIngestion` or `DuplicateBlockProcessing` instead?

2020-09-15 16:40 UTC, Jannis commented
@lutter Totally. Let me update.

2020-09-21 14:15 UTC, Jannis commented
@lutter Updated. How's this?
https://github.com/graphprotocol/graph-node/pull/1903/files#diff-02527213a13f32ef41afb0e0e7e7df5dR743-R748

2020-09-21 18:34 UTC, lutter approved these changes

2020-09-22 15:51 UTC, merged