*: Upgraded dependencies
graphprotocol/graph-node pull request #2004
Opened 2020-11-12 22:24 UTC by That3Percent

Ran `cargo update` for a security audit

2020-11-13 00:07 UTC, leoyvens commented
You can set wasmtime to 0.21.0, the changes we needed have been released.

2020-11-13 19:03 UTC, leoyvens requested changes

2020-11-13 19:03 UTC, leoyvens commented on runtime/wasm/Cargo.toml
>  # Go back to a released version on any version over 0.20.0
Lets remove this comment.

2020-11-16 18:17 UTC, That3Percent commented on runtime/wasm/Cargo.toml
>  # Go back to a released version on any version over 0.20.0
Done.

2020-11-17 18:20 UTC, leoyvens approved these changes

2020-11-17 18:31 UTC, merged