feat: expose playground port
graphprotocol/graph-node pull request #2055
Opened 2020-12-11 18:36 UTC by nachomazzara

2020-12-11 18:45 UTC, leoyvens requested changes

2020-12-11 18:45 UTC, leoyvens commented on docker/Dockerfile
> +# HTTP-PLAYGROUND port
A better description for this is `Indexing status port`

2020-12-11 18:46 UTC, leoyvens approved these changes
Thanks!

2020-12-11 22:06 UTC, leoyvens commented
@nachomazzara looks like this needs a rebase.

2020-12-14 17:32 UTC, nachomazzara commented
@leoyvens  done

2020-12-23 00:19 UTC, nachomazzara commented
any update on this @leoyvens ?

2020-12-23 00:29 UTC, merged