Chunk application of entity modifications
graphprotocol/graph-node pull request #2367
Opened 2021-04-11 16:23 UTC by tilacog

This PR chunks the application of entity modifications as an attempt to fix #2330.

Given that the maximum number of PostgreSQL bind parameters per query is 65535, it makes sense to use N chunks where:

    chunk size = number of fields * number of entities
    N = 65535 / chunk size

Nonetheless, we must remain wary that other parameters other than entity fields are also bound in each query, such as block numbers. 

Therefore, it would be reasonable to reduce `chunk size` by an arbitrary amount to encompass those extra bindings. We can discuss here whether this reduction would be 20, 50, 100 or even more.

2021-04-12 19:35 UTC, lutter requested changes

2021-04-12 19:35 UTC, lutter commented on store/postgres/src/deployment_store.rs
> +const POSTGRES_MAX_BINDINGS_PER_STATEMENT: usize = u16::MAX as usize; // 65535
It might be better to call this `POSTGRES_MAX_PARAMETERS` since that's what the Postgres error message complains about.

2021-04-12 19:35 UTC, lutter commented on store/postgres/src/deployment_store.rs
> +                POSTGRES_MAX_BINDINGS_PER_STATEMENT / num_fields
If you did the chunking inside `Layout.insert_entities`, you know how many parameters each entity needs by looking at `Table.columns.len()` That doesn't account for `block_range` and `vid`, so you'd have to add 2 to that number to be on the safe side (though I don't think we ever write `vid`)

2021-04-13 22:17 UTC, tilacog commented
I've moved the batch size logic so it can access the `table` struct.
I hope I got the numbers right:

- `ClampRangeQuery` always uses 2 binds: one for the `block_number` and another for an `entity_id` array, so we shouldn't worry about it – assuming that an array still counts as one bind.

- `InsertQuery` uses `table.columns.len() + block_id` binds. _(I couldn't find any bindings for `vid, indeed)_.

2021-04-13 22:31 UTC, tilacog commented
I hope I've got the math right:

- `ClampRangeQuery` always uses 2 binds: one for `block_range`and another for the entities id array. Assuming that an array still counts as one bind, I believe there's nothing to do here.
- `InsertQuery` uses one bind for `block_range` and one bind for every column of it's table, so it got batched.

2021-04-13 22:38 UTC, tilacog commented
I've moved the batch logic to the `relational.rs` module, where we can use `table` information.

I hope I got the math right:
- `InsertQuery` uses one bind for `block_range` and one bind for each column in the given table.
- `ClampRangeQuery` always uses 2 binds: one for `block_range` and another for the entity ids array. Assuming that one array uses only one bind, I understand we shouldn't batch it.

2021-04-14 23:40 UTC, lutter requested changes
Yes, I agree on what you say about `ClampRangeQuery` - the one thing to check is if there is some other limit on array size. IIRC, in other contexts it was actually advantageous to break queries with large arrays into smaller ones because you get O(n^2) behavior from scanning these large arrays, so that, for example 10 queries with an array of length 1000 was faster than 1 query with an array of length 10,000

2021-04-14 23:40 UTC, lutter commented on store/postgres/src/relational.rs
> +        let chunk_size = (POSTGRES_MAX_PARAMETERS / table.columns.len()) + 1;
That should be `(POSTGRES_MAX_PARAMETERS / (table.columns.len() + 1))`, right?

2021-04-14 23:40 UTC, lutter commented on store/postgres/src/relational.rs
> +        let chunk_size = (POSTGRES_MAX_PARAMETERS / table.columns.len()) + 1;
Same change in the math here

2021-04-14 23:40 UTC, lutter commented on store/postgres/src/deployment_store.rs
> +        // number of attributes each entity type has.
This comment would now make more sense in the `Layout` methods somewhere

2021-04-16 15:34 UTC, tilacog commented
> Yes, I agree on what you say about `ClampRangeQuery` - the one thing to check is if there is some other limit on array size. IIRC, in other contexts it was actually advantageous to break queries with large arrays into smaller ones because you get O(n^2) behavior from scanning these large arrays, so that, for example 10 queries with an array of length 1000 was faster than 1 query with an array of length 10,000

The [docs state that array size limits are ignored](https://www.postgresql.org/docs/current/arrays.html), but Postgres will complain if the [field size exceeds 1GB](https://www.postgresql.org/docs/current/arrays.html). 
From what I have (quickly) researched, I couldn't any info on what that optimal array size for inserting values would be. 

Do you believe this could be better addressed and reviewed in a new issue/PR?
If so, I can create and assign myself to it.

2021-04-16 15:34 UTC, tilacog commented
> Yes, I agree on what you say about `ClampRangeQuery` - the one thing to check is if there is some other limit on array size. IIRC, in other contexts it was actually advantageous to break queries with large arrays into smaller ones because you get O(n^2) behavior from scanning these large arrays, so that, for example 10 queries with an array of length 1000 was faster than 1 query with an array of length 10,000

The [docs state that array size limits are ignored](https://www.postgresql.org/docs/current/arrays.html), but Postgres will complain if the [field size exceeds 1GB](https://www.postgresql.org/docs/current/arrays.html). 
From what I have (quickly) researched, I couldn't any info on what that optimal array size for inserting values would be. 

Do you believe this could be better addressed and reviewed in a new issue/PR?
If so, I can create and assign myself to it.

2021-04-19 22:38 UTC, lutter approved these changes

2021-04-20 08:44 UTC, merged

2021-04-23 13:00 UTC, v0idpwn approved these changes