Make `AscHeap` dyn-safe
graphprotocol/graph-node pull request #2512
Opened 2021-06-01 20:48 UTC by leoyvens

By moving `try_asc_get`, `asc_get` and `asc_new` out of the trait.

The only real change is in `graph/src/runtime/asc_heap.rs`, the rest is just mechanical refactoring from the fallout.

2021-06-01 21:40 UTC, otaviopace commented
The code seems correct, I just want to know more about the change itself.

Wasn't `AscHeap` already dyn safe? I mean, it had `Sized` as super trait.

This PR probably is to help on something else you're working on, how does it?

2021-06-01 22:05 UTC, leoyvens commented
@otaviopace A trait that has `Sized` as a supertrait is not object safe, because `dyn Foo: !Sized`. It helps on abstracting the runtime for multiblockchain, so that I can write `Box<dyn Fn(&mut dyn AscHeap, u32) -> u32>` as an abstraction for a host function that receives a pointer and returns another.

2021-06-01 23:38 UTC, otaviopace approved these changes

2021-06-02 00:22 UTC, otaviopace requested changes
Changed my mind, I was researching on "sizeness" in Rust and I've found you can remove the `Sized` bound in `trait AscHeap: Sized` and add it to the methods you want like this:

```rust
    fn asc_new<C, T: ?Sized>(&mut self, rust_obj: &T) -> Result<AscPtr<C>, DeterministicHostError>
    where
        Self: Sized,
        C: AscType,
        T: ToAscObj<C>,
    {
        let obj = rust_obj.to_asc_obj(self)?;
        AscPtr::alloc_obj(obj, self)
    }
```

I just added `Self: Sized,` above on the `where` clause.

It will work as long as any of these marked methods don't get called on unsized objects 😉

2021-06-02 13:36 UTC, leoyvens commented
@otaviopace But I do want to call `asc_new` from a `dyn AscHeap`.

2021-06-02 14:44 UTC, otaviopace approved these changes

2021-06-02 14:47 UTC, merged