Sf/block stream future03
graphprotocol/graph-node pull request #2679
Opened 2021-08-02 17:01 UTC by jubeless

- Attempt to upgrade tokio to 1.9 By doing so it would give us the flexibility to upgrade ethabi library as well as tokio-retry library.
-  Modified blockstream implementation to support future 0.3
- Modified cancellable to support future 0.3
- Modified retry lib to support future 0.3. Now retry func expects a future 0.3 function
- Sprinkled some boxed & compat where needed
- Fixed examples
-

2021-08-05 19:21 UTC, leoyvens requested changes
I tried this out in hosted and it is working wonders, I have a few small comments, and then this is ready to merge after a rebase.

2021-08-05 19:21 UTC, leoyvens commented on graph/Cargo.toml
> +reqwest = { version = "0.11.2", features = ["json", "stream", "multipart"] }
The `"trust-dns-resolver"` was accidentally removed here, lets put it back.

2021-08-05 19:21 UTC, leoyvens commented on graph/Cargo.toml
> +tokio-stream = { version = "0.1.6", features = ["sync"] }
Lets bump this back to `0.1.7`.

2021-08-05 19:21 UTC, leoyvens commented on graphql/tests/query.rs
> +            // .unwrap()
Lets remove the commented out code.

2021-08-05 19:21 UTC, leoyvens commented on graph/src/blockchain/block_stream.rs
> +                            // self.state = BlockStreamState::RetryAfterDelay(delay);
Remove commented out code.

2021-08-11 15:10 UTC, jubeless commented
@leoyvens Rebased and fixed the comments! lets get another workflow going

2021-08-11 16:00 UTC, leoyvens approved these changes

2021-08-11 16:04 UTC, merged