CLI tools for persisting entity and POI data for dispute service.
graphprotocol/graph-node pull request #2738
Opened 2021-08-25 17:10 UTC by goaaron

Refactor of #2702  to remove raw sql in place of store libraries. 

Feature additions:
- Subgraph store exposes a `find_all_versions` method that ignores block range clause
- EntityFilter can take a block number  `ChangedAtBlock`
- Layout can `deserialize_with_layout_and_block_range` which will return the block range value with the entity on query. 
- Running CLI is idempotent with new temp directories being generated

Concerns:
- Using the store to query all POI effectuates a `SELECT *`. Not clear how this will break with loading into memory.  Need a cursor or some kind of streaming ingest.

2021-08-30 16:52 UTC, goaaron commented on node/src/bin/manager.rs
> +        /// Optional name of the subgraph. Find this with "SELECT name from subgraphs.subgraph;"
The ID here is the wallet ID belonging to the indexer or an operator. Currently external to graph-node internals.

2021-08-30 18:15 UTC, goaaron commented on store/postgres/src/relational_queries.rs
> +pub struct FindAllVersionsQuery<'a> {
Was misusing EntityQuery.

2021-09-09 23:18 UTC, lutter requested changes

2021-09-09 23:18 UTC, lutter commented on store/postgres/examples/layout.rs
> +            | ColumnType::BlockRange => "Text",
The correct diesel type for `BlockRange` is `Range<Integer>`

2021-09-09 23:18 UTC, lutter commented on store/postgres/src/chain_store.rs
> +
Spurious line addtion

2021-09-09 23:18 UTC, lutter commented on store/postgres/src/chain_store.rs
> +
Spurious line addtion

2022-05-25 11:21 UTC, leoyvens commented
The relevance of this PR is unclear this point, so closing.

2022-05-25 11:21 UTC, closed without merging