Update rust-web3 to ~ v0.15.0
graphprotocol/graph-node pull request #2896
Opened 2021-10-19 16:09 UTC by lutter

There are two things that I'd like to get more input on:

* in `chain/ethereum/src/trigger.rs` we need to deal with `Transaction.from` now being an `Option`, but there's no good way to handle `None`; what was the previous behavior when the raw transaction had no `from`? I couldn't figure that out from the `rust-web3` sources. How should we handle that now? I made that case panic, but that's probably not the best solution.
* in `chain/ethereum/src/transport.rs` we do away with setting the maximum parallelism for HTTP requests. Is that ok?

2021-11-10 09:51 UTC, lutter commented on chain/ethereum/src/trigger.rs
> +        let from = tx.from.expect("tx.from must have a value");
updated the comment

2021-11-10 09:55 UTC, lutter commented on chain/ethereum/src/ethereum_adapter.rs
> -                        const PARITY_OUT_OF_GAS: &str = "Out of gas";
Restored the out of gas check

2021-11-10 09:57 UTC, lutter commented on chain/ethereum/src/ethereum_adapter.rs
> +                                .any(|e| rpc_error.message.contains(e)) =>
Fixed

2021-11-10 09:58 UTC, lutter commented on chain/ethereum/src/ethereum_adapter.rs
> +                        }
Removed

2021-11-10 10:00 UTC, lutter commented on chain/ethereum/src/ethereum_adapter.rs
> +                async move { web3.net().version().await.with_context(|| "boom") }
Less :boom:

2021-11-10 10:24 UTC, lutter commented
Addressed review comments and rebased against latest `master`. I also pushed a branch `lutter/web3-old` that is the original branch for this PR + the fixes from the review. Thanks for the thorough review!

2021-11-12 15:45 UTC, leoyvens requested changes

2021-11-12 15:45 UTC, leoyvens commented on chain/ethereum/src/ethereum_adapter.rs
> -    "out of gas",
This line (and the comment) was lost.

2021-11-12 15:45 UTC, leoyvens commented on chain/ethereum/src/ethereum_adapter.rs
> -                            .chain(GETH_ETH_CALL_ERRORS_ENV.iter().map(|s| s.as_str()));
The logic of chaining with `GETH_ETH_CALL_ERRORS_ENV` was lost.

2021-11-12 15:45 UTC, leoyvens commented
Apologies for the lack of unit tests on this stuff but some of the revert detection logic wasn't fully restored.

2021-11-22 22:26 UTC, lutter commented
> Apologies for the lack of unit tests on this stuff but some of the revert detection logic wasn't fully restored.

Sorry this turned into such a game of whack-a-mole; should be addressed now.

I think the issue isn't the lack of unit tests, but more that there's no separation between the error detection logic and the logic controlling the overall flow of using `eth_call`. One day, I'll factor the former into some sort of helper ;)

2021-11-22 22:45 UTC, lutter commented
Rebased to latest master

2021-11-24 15:15 UTC, leoyvens approved these changes

2021-12-01 23:11 UTC, closed without merging

2021-12-02 21:55 UTC, lutter commented
I made a git mistake when merging this; merged this with commit 39d9c3a5

2021-12-02 21:57 UTC, lutter commented
Before merging, I had run this in the integration cluster with `integer` at 2345ddf5. Only differences were in the bahvior of subgraph failure, where this branch reported one block later than the code in `integer` which is expected