store: Only create exclusion constraints in debug builds
graphprotocol/graph-node pull request #3675
Opened 2022-06-17 02:14 UTC by lutter

In release builds, we create the same index as the exclusion constraint but not the constraint since constraint enforcement is fairly slow. Keeping the constraint for debug builds will have tests that violate the constraint blow up.

We could make that an explicit configuration, but we have so many of them already.

2022-06-20 12:10 UTC, leoyvens requested changes

2022-06-20 12:10 UTC, leoyvens commented on store/postgres/src/catalog.rs
> +const CREATE_EXCLUSION_CONSTRAINT: bool = true;
```suggestion
const CREATE_EXCLUSION_CONSTRAINT: bool = false;
```

2022-06-20 19:16 UTC, lutter commented on store/postgres/src/catalog.rs
> +const CREATE_EXCLUSION_CONSTRAINT: bool = true;
oh wow .. fixed that, thanks!

2022-06-21 10:17 UTC, leoyvens approved these changes

2022-06-21 18:15 UTC, merged