Filipe/substreams option host
graphprotocol/graph-node pull request #3766
Opened 2022-07-22 14:46 UTC by mangas

2022-07-22 15:31 UTC, leoyvens commented
Why isn't it sufficient to use a fake `RuntimeHostBuilder`?

2022-07-22 15:32 UTC, leoyvens commented
Hmm I see that replacing the `RuntimeHostBuilder` isn't so simple.

2022-07-22 15:33 UTC, mangas commented
> Hmm I see that replacing the `RuntimeHostBuilder` isn't so simple.

This way is also more explicit and requires less "hacks" IMO

2022-07-22 15:36 UTC, leoyvens requested changes

2022-07-22 15:36 UTC, leoyvens commented on core/src/subgraph/instance.rs
>              let module_bytes = data_source.runtime();
What about making this controlled by the data source, so we change `DataSource::runtime` to return an option, and if it returns none then no host is created.

2022-07-25 14:02 UTC, leoyvens requested changes

2022-07-25 14:02 UTC, leoyvens commented on runtime/wasm/src/host.rs
> +        raw_module: &Vec<u8>,
```suggestion
        raw_module: &[u8],
```

2022-07-25 14:02 UTC, leoyvens commented on runtime/wasm/src/mapping.rs
> +    raw_module: &Vec<u8>,
```suggestion
    raw_module: &[u8],
```

2022-07-25 15:38 UTC, leoyvens approved these changes

2022-07-25 19:26 UTC, merged