graphql: alternative sytnax for AND/OR
graphprotocol/graph-node pull request #4080
Opened 2022-10-20 01:12 UTC by saihaj

introduces alternative syntax for doing `AND/OR` filters.

Generated filter will have these new types
```graphql
input Proposal_fitler {
  id: ID
  # ... other variants of `id` like we do today
  collection: String
  # ... other variants of `collection` like we do today
  and: [Proposal_filter]
  or: [Proposal_filter]
}
```

### Example queries
1. using multiple AND filters
```graphql
query {
  proposals(
    where: { and: [{ id_in: "111" }, { collection_contains_nocase: "a" }] }
  ) {
    id
  }
}
```

2. Using multiple OR filters
```graphql
query {
  proposals(
    where: { or: [{ id_in: "111" }, { collection_contains_nocase: "a" }] }
  ) {
    id
  }
}
```
3. Using AND/OR combined
```graphql
query {
  proposals(
    where: {
      or: [{ id_in: "111" }, { collection_contains_nocase: "a" }]
      and: [{ owner_contains: "0x2" }]
    }
  ) {
    id
  }
}
```

Downside with this approach is users can still have nested `AND`/`OR` which can be quite expensive example
```graphql
query {
  proposals(
    where: {
      or: [
        { id_in: "111" }
        {
          collection_contains_nocase: "a"
          and: [{ owner_contains: "0x2" }, { id_in: "22" }]
        }
      ]
      and: [{ owner_contains: "0x2" }]
    }
  ) {
    id
  }
}
```

2022-10-20 23:42 UTC, lutter commented
I am still trying to wrap my head around what this all means - the notation that GraphQL imposes on us makes this all pretty confusing.

If I have predicates `a`, `b`, `c`, etc. where each predicate is something like `name: "Truss"`, `where: { a, b, c }` and `where: { and: [a, b, c] }` mean the same thing. It gets more murky with
```
where: {
  and: [a, b],
  or: [c, d]
}
```
because we need to define precedence rules. I would expect the above to mean `(a and b) or c or d`. That, I think, could also be written as `where: { or: [ {and: [a, b]}, c, d] }`.

I wonder if we should enforce the latter notation by making it illegal to have `and` and `or` at the same level, since the more explicit notation of  `where: { or: [ {and: [a, b]}, c, d] }` is much clearer.

There's also the mixed case of `where: { a, b, or: [c, d] }` which would mean `a and b and (c or d)` and also useless cases like `where: {a, b, and: [c, d] }` which is the same as `where: {a, b, c, d}`

As for this being expensive: if people start using `or` a lot, especially with no additional constraints, that can become very expensive; I haven't tried it but something like `where: { or: [{token_0: "ABC"}, {token_1: "ABC"}] }` OTOH, we already have plenty of ways to write expensive queries.

2022-10-21 11:48 UTC, azf20 commented
Thanks so much @saihaj! I think this is close.. I wonder if we can address some of @lutter's concerns by making the approaches exclusive, i.e. the filter can only be one of the following:

Retained for backwards compatibility & simplicity:
```
input Proposal_original_filter {
  id: ID
  # ... other variants of `id` like we do today
  collection: String
}
```

Allows for "or conditions":
```
input Proposal_and_filter {
  or: [Proposal_filter]
}
```

Allows for more nuanced AND filtering, sub-filters with OR etc:
```
input Proposal_or_filter {
  and: [Proposal_filter]
}
```

So in summary:

```
input Proposal_filter = Proposal_original_filter | Proposal_and_filter | Proposal_or_filter
```

2022-10-24 15:40 UTC, azf20 commented
@saihaj assuming yes, @lutter and I just caught up and this syntax looks good to go, but I think we will just want to add a check to prevent `and and or` filters at the same level, if that makes sense? Otherwise I think this is ready for review

2022-10-27 15:42 UTC, azf20 commented
@saihaj as this is still in draft, just let us know when this is ready to take a look!

2022-11-08 16:32 UTC, lutter commented
One thing: it would be good if there was an (undocumented) feature flag `GRAPH_GRAPHQL_DISABLE_BOOL_FILTERS` to turn off boolean filters. I am not sure how hard it will be to get that in, but if we could control at least whether `or` can be used would be very good as that has the highest potential to create slow queries. Turning off `or` should happen at the point where we parse filters and just result in a `QueryExecutionError::NotSupported` or some such. The flag should default to `false` (i.e., we accept filters by default)

2022-11-09 14:49 UTC, lutter requested changes
This all looks good, you just need to add the environment variable that allows disabling boolean filters

2022-11-09 14:49 UTC, lutter commented on graphql/src/store/query.rs
> +                Or => EntityFilter::Or(build_list_filter_from_object(entity, object, schema)?),
These two branches should check whether boolean filters are disabled and return a `QueryExecutionError` if they are.

2022-11-09 14:49 UTC, lutter commented on graphql/src/schema/api.rs
> +
These two statements should only be executed if boolean filters are not disabled

2022-11-09 16:18 UTC, lutter approved these changes
Nice! Looks great now!

2022-11-10 00:42 UTC, dotansimha approved these changes

2022-11-10 02:16 UTC, merged