docs: update links to graph tooling repo
graphprotocol/graph-node pull request #4303
Opened 2023-01-19 20:41 UTC by saihaj

2023-01-19 20:42 UTC, saihaj commented on tests/integration-tests/data-source-revert/package.json
> +    "@graphprotocol/graph-ts": "latest"
I think this is better and safer cause essentially we want to try new features

2023-01-20 10:24 UTC, enisdenjo approved these changes

2023-01-20 10:36 UTC, dotansimha approved these changes

2023-01-20 10:37 UTC, dotansimha commented on tests/integration-tests/data-source-revert/package.json
> +    "@graphprotocol/graph-ts": "latest"
Agree!

2023-01-23 14:03 UTC, neysofu requested changes

2023-01-23 14:03 UTC, neysofu commented on tests/integration-tests/data-source-revert/package.json
> +    "@graphprotocol/graph-ts": "latest"
I like the idea, but we must find another way to periodically upgrade our dependencies without `latest`. `yarn.lock` exists specifically to make builds as deterministic as possible, and an upstream change should never break our builds (case in point, CI fails now). I'm working on a PoC with a Dependabot-like workflow, so I'll post more information here. Until then, all of these version changes have to be reverted so the CI succeeds.

2023-01-23 16:10 UTC, neysofu commented on tests/integration-tests/data-source-revert/package.json
> +    "@graphprotocol/graph-ts": "latest"
Alright, I think I got it. `latest` can stay. We just need to 1. modify `dependabot.yml` and 2. rebuild `yarn.lock`.
@saihaj you can cherrypick from my branch `filippo/yarn-lock-dependabot` if necessary (`https://github.com/graphprotocol/graph-node/commit/592aeae2f6b204b991fc2334161045ad761b583c` and `https://github.com/graphprotocol/graph-node/commit/b1d3633c9c87aedf100f060a99b1e8da7daf17b9`).

2023-02-06 16:32 UTC, neysofu commented
@saihaj I saw your message on Slack - I've tried to get this thing working, but no luck. It might require us to upgrade Yarn to v2 or v3 to leverage their new workspace commands...

If you're okay with leaving the `latest` thing out of this PR to revisit it down the road, I think that would be the best course of action.

2023-02-06 21:32 UTC, saihaj commented
> If you're okay with leaving the latest thing out of this PR to revisit it down the road, I think that would be the best course of action.

This issue is we have moved combined `graph-cli` and `graph-ts` to monorepo so this is just easier to do

2023-02-08 15:08 UTC, neysofu commented
Well, agreed, if we could get it to compile that would be best. Feel free to experiment with it and see if you can get it working.

2023-03-22 03:27 UTC, saihaj commented
> hey @neysofu and @saihaj, any update on this, is this blocked or are there changes required here?

need to spend sometime debugging this one but haven't gotten to it yet. Putting this in draft for now

2023-05-26 17:43 UTC, merged