Add a flag to graphman to list all deployments, Fixes #3407
graphprotocol/graph-node pull request #4347
Opened 2023-02-07 15:59 UTC by incrypto32

Fixes #3407

2023-02-13 23:47 UTC, lutter requested changes
Looks great! Just change how the error is returned using `bail!` and we can merge this

2023-02-13 23:47 UTC, lutter commented on node/src/bin/manager.rs
> +                        std::process::exit(1);
You can just `bail!("Please specify a deployment or use --all to list all deployments)` here (using `anyhow::bail!`) - that's what all other errors end up doing and there's no need to explicitly `exit(1)`

2023-02-13 23:47 UTC, lutter commented on node/src/manager/deployment.rs
> +            DeploymentSearch::All => write!(f, ""),
you could just do `{ Ok(()) }` here and not call `write!` at all

2023-02-14 12:59 UTC, incrypto32 commented
@lutter Im not sure why the integration tests fail, let me know if i can mark this PR ready for review.

2023-02-15 00:05 UTC, lutter approved these changes
This looks great, and is ready to be merged (pending some unrelated fixes to our CI)

Before merging, can you squash all the commits into one and use this commit message:
```
node: Add a flag to graphman to list all deployments 

Fixes https://github.com/graphprotocol/graph-node/issues/3407
```

2023-02-17 23:52 UTC, lutter commented
The integration tests are fixed now; just rebase your changes on top of the latest master, and all checks should pass

2023-02-18 05:28 UTC, incrypto32 commented
@lutter  looks like all tests passed!

2023-02-24 20:06 UTC, merged