Fulltext filter sort
graphprotocol/graph-node pull request #4413
Opened 2023-03-03 00:05 UTC by flametuner

I explained more my usecase why I need this feature on #4412.

There's also another issue #1823, where this PR can be useful.

I started working on the codebase in the last 2 days so I may not see all the possibles edge cases where this code can fail, feel free to review.

2023-03-03 00:06 UTC, flametuner commented
The filtering part was almost trivial, but the sorting part was really trick I hope this code can be useful.

2023-03-09 01:18 UTC, lutter requested changes
I've only had time to review the first commit - thanks for that, not being able to filter by more than just text has been a longstanding issue.

There should be a test for that functionality; the best place to put that is probably [here](https://github.com/graphprotocol/graph-node/blob/master/graphql/tests/query.rs) since that will test the full code path of running a GraphQL query with this new feature.

For the sorting part, I'll need some more time to review that; from what I have seen, the main point is to make it possible to order by more than one column. That has some implications for the cursor work ([draft](https://github.com/graphprotocol/graph-node/pull/3214))

I think it would be best to split this PR into two: one that fixes filtering, and one that adds multi-column sorting

2023-03-09 19:43 UTC, flametuner commented on graphql/src/store/query.rs
> +        _ => Ok(Some(EntityFilter::And(entity_filter)))
The `where_filter` is currently returnning a `Vec<EntityFilter>`, but I think I can chain `EntityFilter::And([text_filter, EntityFilter::And(where_filter)])` with no problems.

2023-03-09 19:53 UTC, flametuner commented on graphql/src/store/query.rs
> +    };
Done.

2023-03-09 19:53 UTC, flametuner commented on graphql/src/store/query.rs
> +    };
Done.

2023-03-10 00:21 UTC, flametuner commented
> I think it would be best to split this PR into two: one that fixes filtering, and one that adds multi-column sorting

@lutter, I'll close this PR and create another one for just filter and the test. After the filter (and cursor) is merged, I can create another with the sorting.

2023-03-10 00:21 UTC, closed without merging