graph: fix substreams `startBlock` selection
graphprotocol/graph-node pull request #4463
Opened 2023-03-16 03:59 UTC by YaroShkvorets

This fixes #4449 by choosing `initial_block` of the module provided in the manifest.

It also verifies that module name provided in the subgraph manifest exists in the substreams manifest and if not, `graph deploy` errors out rather than letting it deploy and then unsuccessfully retry RPC requests to the substreams endpoint.

2023-03-16 04:45 UTC, YaroShkvorets commented
Oh. Making it pass those tests would be non-trivial without the substreams package...

2023-03-17 15:22 UTC, YaroShkvorets commented
Ready for review

2023-03-17 15:31 UTC, maoueh requested changes

2023-03-17 15:31 UTC, maoueh commented on chain/substreams/src/data_source.rs
> +                }],
Actually, could you add a second module with a different block so we see the code is working properly.

2023-03-17 17:18 UTC, maoueh approved these changes
Once the tests pass, I'll merge this.

2023-03-17 18:17 UTC, merged