Cache only correct eth_call data
graphprotocol/graph-node pull request #4879
Opened 2023-09-19 17:01 UTC by SozinM

This PR closes https://github.com/graphprotocol/graph-node/issues/4756 
It changes caching logic to cache only correct and decodable eth_calls to prevent cache from providing faulty data

This PR is still WIP

2023-09-22 12:21 UTC, SozinM commented on chain/ethereum/src/ethereum_adapter.rs
> +                        .map(move |result| result.0),
I feel like this could take a bit of refactoring, but I'm not sure it's possible to make it more nice looking

2023-09-22 12:21 UTC, SozinM commented on chain/ethereum/src/ethereum_adapter.rs
> +        let cache = cache.clone();
I would like to move it to more deep scope, but I cannot wrap my head on how to correctly clone it in and_then future.

2023-09-22 12:21 UTC, SozinM commented on chain/ethereum/src/ethereum_adapter.rs
> +                    let _ = graph::spawn_blocking_allow_panic(move || {
I think I could move it to dedicated and_then future using https://docs.rs/futures-async-combinators/latest/futures_async_combinators/future/fn.and_then.html
But I didn't see it usage in the graph so I'm hesitant to add this

2023-10-23 18:42 UTC, lutter requested changes
First off, congrats on making it through this code - it's really gnarly and would hugely benefit from asyncifying (though that might be quite a bit of an undertaking)

Before merging this, we need to find a way to not call `set_call` for calls that are already in the cache as that will have a bad effect on performance.

2023-11-13 17:58 UTC, azf20 commented
hey @SozinM, thanks so much for this PR! Did you manage to take a look at David's comments?

2023-11-24 12:52 UTC, SozinM commented
Hi!
Yes, I did saw
I will fix them once I return to work (in dec)

2024-01-04 17:38 UTC, merged