Add more labels to `deployment_sync_secs`
graphprotocol/graph-node pull request #4965
Opened 2023-11-02 14:59 UTC by zorancv

Addressing https://github.com/graphprotocol/graph-node/issues/4943

2023-11-02 21:40 UTC, lutter requested changes
This looks good. There are some compile/test failures that need to be addressed.

2023-11-02 21:40 UTC, lutter commented on graph/src/components/metrics/stopwatch.rs
> +                .get_metric_with_label_values(&[section, &self.stage, &&self.shard])
The double `&&` shouldn't be needed, just one `&` should be enough.

2023-11-06 18:31 UTC, zorancv commented
@lutter I believe that the issues are addressed.

2023-11-14 08:32 UTC, lutter approved these changes

2023-11-16 11:41 UTC, merged