Rework generation of the VID
graphprotocol/graph-node pull request #5737
Opened 2024-12-18 15:25 UTC by zorancv

2025-01-09 00:27 UTC, lutter requested changes
A general question: we already require that every `Entity` has an `id`, if it doesn't, things will fail in funky ways. Wouldn't it be simpler to just treat the `vid` as another attribute of `Entity`, i.e., require that `entity.get("vid")` always returns something instead of keeping it separate from the entity?

2025-01-09 00:27 UTC, lutter commented on graph/src/components/store/entity_cache.rs
> +    pub vid_seq: i32,
Why is this an `i32`? Shouldn't it be a `u32`?

2025-01-09 00:27 UTC, lutter commented on store/postgres/src/relational/ddl.rs
> +        let vid_type = if self.object.is_poi() || !self.object.is_object_type() {
Strictly speaking, for POI it doesn't matter, and there's never instances of interfaces (only objects that implement an interface), but I think for simplicity, it might be best to autogenerate a vid for every kind of entity we deal with.

2025-01-09 16:17 UTC, zorancv commented on graph/src/components/store/entity_cache.rs
> +    pub vid_seq: i32,
My mistake. Good catch!

2025-01-10 15:05 UTC, zorancv commented on store/postgres/src/relational/ddl.rs
> +        let vid_type = if self.object.is_poi() || !self.object.is_object_type() {
So you would prefer that all is generated by us rather than from the database? Is there inconsistency concern regarding the aggregation (that one is more involved)?

2025-01-14 13:35 UTC, zorancv commented on store/postgres/src/relational/ddl.rs
> +        let vid_type = if self.object.is_poi() || !self.object.is_object_type() {
There is a PR https://github.com/graphprotocol/graph-node/pull/5770 that disables aggregations entities as source entities for now.

2025-01-20 16:20 UTC, zorancv commented
> A general question: we already require that every `Entity` has an `id`, if it doesn't, things will fail in funky ways. Wouldn't it be simpler to just treat the `vid` as another attribute of `Entity`, i.e., require that `entity.get("vid")` always returns something instead of keeping it separate from the entity?

@lutter I've decided to go that route. It simplifies the code a lot. Also I've added a check in the `EntityCache`  `set()` that there was no `vid` previously set.

2025-01-28 22:29 UTC, lutter commented on graph/src/components/store/entity_cache.rs
> +        assert!(old_vid.is_none());
This shouldn't be an assertion - tripping that would take the whole server down. Instead, it should return an error so that only this subgraph is affected.

2025-01-28 22:47 UTC, lutter reviewed
This looks good. I'd mostly just like to understand better what is happening with the explicit block number for the PoI.

Also, I don't think there are any tests that ensure that the vid's are indeed set by insertion order. It would be good to have a test for the `EntityCache` that ensures that.

2025-01-28 22:47 UTC, lutter commented on graph/src/data/store/mod.rs
> +        self.get("vid")
It would be better to have a constant `VID: &str = "vid"` to guard against typos. There might even be one defined somewhere already

2025-01-28 22:47 UTC, lutter commented on graph/src/data/subgraph/api_version.rs
> +// based on block number and the sequence of the entities in a block.
This should also mention that ordering by `vid` now, across all entity types for a subgraph, returns entities in the order in which they were written.

2025-01-28 22:47 UTC, lutter commented on graph/src/schema/input/mod.rs
> +const VID_FIELD: &str = "vid";
There is a constant, yay!

2025-01-28 22:47 UTC, lutter commented on store/postgres/src/relational/ddl.rs
> +        let vid_type = if !self.object.is_object_type() {
This would be easier to read if it was not negated. And maybe has a comment that the `vid` of aggregations are not necessarily in insertion order

2025-01-28 22:47 UTC, lutter commented on store/postgres/src/relational/prune.rs
> -
Is this also correct for aggregations since they still have a vid sequence?

2025-01-28 22:47 UTC, lutter commented on store/postgres/src/relational_queries.rs
> +                    if key == "vid" {
There's a lot of literal `"vid"` strings here, it would be better to use a constant.

2025-01-28 22:47 UTC, lutter commented on graph/src/components/store/entity_cache.rs
> +// Number of VIDs that are reserved ourside of the generated ones here.
typo: s/ourside/outside/

2025-01-28 22:47 UTC, lutter commented on core/src/subgraph/runner.rs
> +    let block_number = proof_of_indexing.get_block();
I didn't quite understand what's happening here with the PoI block number. Why is this needed?

2025-01-28 22:50 UTC, lutter commented on graph/src/data/store/mod.rs
> +    }
One additional thought: it would be great if we could guarantee that an entity is always constructed with the `vid` set, similar to how that's done for the `id`. I haven't checked how much work that is, but it would make the various expects sprinkled around here easier to accept.

2025-01-29 16:30 UTC, zorancv commented on core/src/subgraph/runner.rs
> +    let block_number = proof_of_indexing.get_block();
PIO like other entities has a VID generated by us, and for that we also need a block number.

2025-01-29 22:17 UTC, zorancv commented on graph/src/data/store/mod.rs
> +    }
I like the suggestion but would like to postpone it together with the testing request above for a later stage. WDYT?

2025-01-30 16:51 UTC, zorancv commented on graph/src/data/store/mod.rs
> +    }
The test for the VID order is implemented now: https://github.com/graphprotocol/graph-node/pull/5737/commits/166c9098c4c9a6ae2464706b6d4e4dc79746e6d3

2025-01-31 01:24 UTC, lutter commented on graph/src/data/store/mod.rs
> +    }
I am fine with postponing the enforcement of having a `vid`

2025-01-31 01:36 UTC, lutter approved these changes
Nice! I left some minor stylistic comments, would be great to address them, but I am totally fine with merging this.

2025-01-31 01:36 UTC, lutter commented on graph/src/components/store/entity_cache.rs
> +            bail!("VID was already present when set in EntityCache");
This is very very minor but in these error messages it's very helpful if it includes the entity that is involved (type and id) and what the old vid was.

2025-01-31 01:36 UTC, lutter commented on graph/src/data/subgraph/api_version.rs
> +// representing the writting order of all entity types in a subgraph.
Typo: "The latter represents the write order across all entity types in the subgraph"

2025-01-31 01:36 UTC, lutter commented on store/postgres/src/relational/prune.rs
> +        let old_vid_form = !self.src.object.is_object_type();
This is also very minor: since we are now using `!EntityType.is_object_type()` in a few places to indicate whether the type has/should have a `vid` sequence, it would be cleaner if there was a helper `EntityType.has_vid_seq()` since that makes it clear what this check is asking for. (the impl of the method would just be `!self.is_object_type()`)

2025-01-31 01:36 UTC, lutter commented on store/postgres/src/relational/prune.rs
> +        if old_vid_form {
Also minor, but this could just be
```rust
if self.src.object.has_vid_seq() {
    let vid_seq = format!("{}_{VID_COLUMN}_seq", self.src.name);
    writeln!(..)
}
```

2025-01-31 01:36 UTC, lutter commented on store/postgres/src/relational_queries.rs
> +        let new_vid_form = self.table.object.is_object_type();
Similarly, this could say `self.table.object.has_vid_seq()` which is also a little clearer than trying to remember what old and new vid forms are

2025-01-31 07:55 UTC, zorancv commented on store/postgres/src/relational/prune.rs
> +        let old_vid_form = !self.src.object.is_object_type();
Addressed in the next PR in https://github.com/graphprotocol/graph-node/pull/5782/commits/522d7f79aab981188c3fedf5521d1d5db212a8dd

2025-01-31 07:55 UTC, zorancv commented on store/postgres/src/relational/prune.rs
> +        if old_vid_form {
Addressed in the next PR in https://github.com/graphprotocol/graph-node/pull/5782/commits/522d7f79aab981188c3fedf5521d1d5db212a8dd

2025-01-31 07:56 UTC, zorancv commented on store/postgres/src/relational_queries.rs
> +        let new_vid_form = self.table.object.is_object_type();
Addressed in the next PR in https://github.com/graphprotocol/graph-node/pull/5782/commits/522d7f79aab981188c3fedf5521d1d5db212a8dd

2025-01-31 20:15 UTC, lutter commented on store/postgres/src/relational/prune.rs
> +        if old_vid_form {
Not sure where best to leave that comment (and maybe I am missing something with all the rebasing etc.) but you'll need two different helpers on `EntityType`: `strict_vid_order()` is just a check based on the spec version, and `has_vid_seq()` is a check that uses both `strict_vid_order()` and whether we are dealing with a normal object type or an aggregation. In the commit I saw, it looked like `strict_vid_order()` was now being used in places that should use `has_vid_seq()`

2025-02-25 07:00 UTC, closed without merging