Implement @derivedFrom for non-list fields
graphprotocol/graph-node pull request #837
Opened 2019-03-25 14:15 UTC by Jannis

This allows to define types like
```graphql
type Domain @entity {
  id: ID!
  ...
}

type DomainAuction @entity {
  id: ID!
  domain: Domain @derivedFrom(field: "id")
  ...
}
```
and resolve them in queries by virtue of the two sides sharing the same ID.

2019-03-25 14:45 UTC, Jannis commented
Updated the tests to include `@derivedFrom` on a non-list field.

2019-03-25 14:58 UTC, leodasvacas commented
As we were discussing on Discord, if more than one entity has the matching id, this may return any of the matching entities as the value. We can consider that to be a logic error by the user, but we don't catch it in any way. So I'm not confortable merging until we either come up with a better solution or at least have a wider discussion to check if we are ok with the implications.

2019-03-25 17:02 UTC, Jannis commented
Ideas:

* We could query matches with `first: 2` instead of `first: 1` and return a GraphQL error if there is more than one. This is the easiest solution, but makes the user deal with the problem rather than the subgraph author.

* When writing an entity, we could check if there are any non-list `@derivedFrom` fields that involve the entity type. If there are any, check if there already is an entity of the same entity type that matches that `@derivedFrom`. If that's the case fail, similar to how we fail with ID clashes for interfaces.

2019-03-25 17:27 UTC, leodasvacas commented
@Jannis I think the first idea is good enough to allow landing this.

Having an integrity check that prevents the situation from arising is good in theory, but it's complicated. Your second idea solves half of the problem, but there is also the case that two entities already exist referencing the same id, and then a deriving entity with that id is added.

2019-03-26 14:35 UTC, Jannis commented
@leodasvacas Ok, first approach implemented!

2019-03-26 14:46 UTC, leoyvens requested changes
Looking good, can we get a test for the `AmbiguousDerivedResult` error?

2019-03-26 14:51 UTC, Jannis commented
@leodasvacas I guess... 😬

2019-03-26 19:15 UTC, leoyvens approved these changes

2019-03-26 19:25 UTC, merged