Add a `log.log` host export for basic logging in mappings
graphprotocol/graph-node pull request #943
Opened 2019-05-14 19:34 UTC by Jannis

Part of resolving #599 and https://github.com/graphprotocol/graph-ts/issues/5.

2019-05-14 19:36 UTC, Jannis commented
I'll add a test for `log.log` tomorrow.

2019-05-15 08:32 UTC, Jannis commented
I've come to the conclusion that there's no simple/good way to capture and check the `log.log`, so I'd rather not add a test for it.

2019-05-15 15:30 UTC, leoyvens requested changes
Yay logging! Just a comment.

2019-05-15 15:30 UTC, leodasvacas commented on runtime/wasm/src/asc_abi/class.rs
> +#[repr(C)]
This should be `#[repr(u32)]`.

2019-05-15 17:35 UTC, Jannis commented on runtime/wasm/src/asc_abi/class.rs
> +#[repr(C)]
@leodasvacas Updated to `#[repr(u32)]`!

2019-05-15 17:46 UTC, leoyvens approved these changes

2019-05-15 18:04 UTC, merged