Add LRU cache (50 files) to `LinkResolver`
graphprotocol/graph-node pull request #993
Opened 2019-06-07 13:46 UTC by Jannis

Resolves #992.

This avoids unnecessary roundtrips to IPFS for files that are requested again and again in quick succession, as is the case with data sources created from the same templates.

2019-06-07 18:01 UTC, leoyvens requested changes
Besides the minor comment, I'm concerned about the total size of the cache. 50*MAX_IPFS_MAP_FILE_SIZE is 12GB, this could hog memory and even be an attack vector. We have to limit the size further somehow, I propose that we only cache small files, even though we still allow fetching large files.

2019-06-07 18:07 UTC, Jannis commented on runtime/wasm/src/host_exports.rs
> +        module: &WasmiModule<E, L, S, U>,
Yep

2019-06-07 18:07 UTC, Jannis commented
@leodasvacas That's a good point. I'll update the PR and also make the cache size configurable.

2019-06-08 21:28 UTC, Jannis commented
@leodasvacas Updated. See the latest commit (https://github.com/graphprotocol/graph-node/pull/993/commits/7c91bb4895bb6c6dd5d1fd109181716e325c4b41) in this PR:

> **core: Add limits for IPFS cache and cache file sizes**
>
> The maximum cache capacity is now controlled by the `GRAPH_MAX_IPFS_CACHE_SIZE` environment variable. Only files smaller than or equal to `GRAPH_MAX_IPFS_CACHE_FILE_SIZE` are cached. Larger files are always loaded from IPFS.

2019-06-08 21:29 UTC, Jannis commented
I still need to add these vars to `docs/`.

2019-06-08 21:31 UTC, Jannis commented
...and that is now done as well.

2019-06-10 14:57 UTC, leodasvacas commented
Changes look good, but according to CI this is not compiling.

2019-06-11 12:29 UTC, Jannis commented
@leodasvacas Updated once more. Should pass the test suite now.

2019-06-11 14:34 UTC, leoyvens approved these changes

2019-06-11 14:42 UTC, merged